#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys
import Tkinter
from Tkinter import *
#from Canvas import Rectangle, CanvasText, Group, Window
#import random

H1 = PhotoImage(file="cards/HA.gif")

def cardsValue(self):	
	x = {'H1':1}
	
	for i in x:
		global y
		y = x[i]
		return y

cardsValue('H1')
print y
